language: c

dist: trusty


services:
  - postgresql

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
  - psql -c 'create role gabor;' -U postgres
  - psql -c "alter role gabor with password 'gabor';" -U postgres
  - psql -c "alter role gabor login;" -U postgres
  - psql -c 'create database testje;' -U postgres
  - psql -c 'grant all privileges on database testje to gabor;' -U postgres
  - psql -c 'create table boeken (id integer, titel varchar(100));' -U gabor -d testje
  - psql -c "insert into boeken values(1,'handboek')" -U gabor -d testje
  - psql -c "insert into boeken values(2,'telefoongids')" -U gabor -d testje

before_install:
  - sudo chmod 777 /var/log/syslog
  - sudo ln -s /usr/bin/make /usr/bin/gmake
  - sudo sudo apt-get install libbsd-dev libpq-dev
  - sudo mkdir locallibs; cd locallibs
  - sudo wget https://download.libsodium.org/libsodium/releases/libsodium-stable-2018-03-10.tar.gz
  - sudo tar zvxf libsodium-stable-2018-03-10.tar.gz ; cd libsodium-stable ; sudo ./configure ; sudo make ; sudo make install
  - sudo ls -la /etc
  - sudo ls -la /etc/ld.so.conf.d
  - sudo echo "/usr/local/lib/*" > /etc/ld.so.conf.d/liblocal.conf
  - sudo rm /etc/ld.so.cache
  - sudo ldconfig
  - cd ..

script: ./runtests.sh
