language: c

dist: trusty
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

before_install:
  - sudo chmod 777 /var/log/syslog
  - sudo ln -s /usr/bin/make /usr/bin/gmake
  - sudo sudo apt-get install libbsd-dev
  - export TZ=Europe/Amsterdam
  
script: ./runtests.sh
