language: c

dist: trusty

before_install:
  - sudo chmod 777 /var/log/syslog
  - sudo ln -s /usr/bin/make /usr/bin/gmake
  - sudo sudo apt-get install libbsd-dev
  - sudo ls -la /etc
  - sudo touch /etc/ld.so.conf.d/liblocal.conf
  - sudo chmod uog+w /etc/ld.so.conf.d/liblocal.conf
  - sudo ls -la /etc/ld.so.conf.d
  - sudo echo "/usr/local/lib/*" > /etc/ld.so.conf.d/liblocal.conf
  - sudo rm /etc/ld.so.cache
  - sudo ldconfig

script: ./runtests.sh
